### PR TITLE
(feat): show check icon on copy button press with animation

### PR DESCRIPTION
**Pull request by AhmedAli125**
Fix issue #40 # show check icon on copy button press with animation of fade in and out with 300ms

### CODE REVIEW

**Comment by AhmedAli125** [comment]
> @AhmedAli125 can you share a recording/screenshot to share how it looks?

https://user-images.githubusercontent.com/54624746/138225047-feda870c-9a30-4106-8599-ba64335c3d68.mp4

**Comment by AhsanAyaz** [comment]
Looks great! Thanks @AhmedAli125

**Comment by AhsanAyaz** [comment]
Btw, another approach would've been to just add a class/remove the class from the elements to trigger the animation

**Comment by AhmedAli125** [comment]
> Btw, another approach would've been to just add a class/remove the class from the elements to trigger the animation

Thankyou for highlighting this approach. Will surely use this in future

**Pull request merged**
